name: test dev

on:
  push:
    branches: [master, main]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Use Common Workflow
        uses: HusanIftikhar/common-work-flow@master
        with:
          workflow-file: '.github/workflows/security-analysis.yaml'
