name: test dev

on:
  push:
    branches: [master, main]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test Workflow
        run: |
          echo "hello world"
      - name: Use Common Workflow
        uses: HusanIftikhar/common-work-flow@main
        with:
          workflow-file: '.github/workflows/security-analysis.yaml'