name: test workflow

on:
  push:
    branches: [main]
 
jobs:
    test-workflow:
        runs-on: ubuntu-latest
        steps:
         - name: test work flow run
           run: |
            echo "hello world"      